{% set name = "coreapi-cli" %}
{% set version = "1.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d76b5320ea9ad04d922001ac8897b903a7a359c08a53822f819134c50aa22c5f

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click
    - python-coreapi

test:
  requires:
    - python {{ python_min }}
  commands:
    - coreapi --help

about:
  home: https://github.com/core-api/coreapi-cli
  license: BSD
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.md'
  summary: 'An interactive command line client for Core API.'

extra:
  recipe-maintainers:
    - scopatz
